<?php
return [
    'BE' => [
        'adminOnly' => 0,
        'compressionLevel' => '9',
        'debug' => true,
        'entryPoint' => '/typo3',
        'installToolPassword' => '$argon2i$v=19$m=65536,t=16,p=1$amhzZjFyWG1USGg1MGVNRg$q1rfFE3Qx3PQes8d4srA5+pe7qgr5E92gft0AoSpmEs',
        'lockSSL' => true,
        'passwordHashing' => [
            'className' => 'TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\Argon2iPasswordHash',
            'options' => [],
        ],
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8mb4',
                'dbname' => 'usr_p702247_2',
                'defaultTableOptions' => [
                    'charset' => 'utf8mb4',
                    'collation' => 'utf8mb4_unicode_ci',
                ],
                'driver' => 'mysqli',
                'host' => 'db003424.mydbserver.com',
                'password' => '07o0mPM=b%!r',
                'port' => 3306,
                'user' => 'p702247',
            ],
        ],
    ],
    'EXTCONF' => [
        'lang' => [
            'availableLanguages' => [
                'de',
                'fr',
                'it',
                'mi',
            ],
        ],
    ],
    'EXTENSIONS' => [
        'backend' => [
            'backendFavicon' => '',
            'backendLogo' => '',
            'loginBackgroundImage' => '',
            'loginFootnote' => '',
            'loginHighlightColor' => '#8bb83b',
            'loginLogo' => 'EXT:vt13sitepackage/Resources/Public/img/innovatech_logo_green.svg',
            'loginLogoAlt' => '',
        ],
        'extensionmanager' => [
            'automaticInstallation' => '1',
            'offlineMode' => '0',
        ],
        'image_jack' => [
            'avif' => [
                'active' => '0',
                'converter' => 'im',
                'mimeTypes' => [
                    'gif' => '1',
                    'jpeg' => '1',
                    'png' => '1',
                ],
                'options' => '-sharpen 1 -quality 75 -define avif:speed=0 -define avif:lossless=false +profile "*"',
            ],
            'jpeg' => [
                'active' => '1',
                'path' => '/usr/local/bin/jpegoptim',
            ],
            'logging' => [
                'alerts' => '1',
                'critical' => '1',
                'debugs' => '0',
                'emergencies' => '1',
                'errors' => '1',
                'infos' => '0',
                'notices' => '0',
                'warnings' => '0',
            ],
            'png' => [
                'active' => '0',
                'path' => '/usr/local/bin/optipng',
            ],
            'useFallbackDriver' => '0',
            'useLiveProcessing' => '1',
            'useSafeProcessing' => '0',
            'webp' => [
                'active' => '1',
                'converter' => 'im',
                'mimeTypes' => [
                    'gif' => '1',
                    'jpeg' => '1',
                    'png' => '1',
                ],
                'options' => '-sharpen 1 -quality 75 -define webp:lossless=false -define webp:method=6',
            ],
        ],
        'indexed_search' => [
            'catdoc' => '/usr/bin/',
            'deleteFromIndexAfterEditing' => '1',
            'disableFrontendIndexing' => '0',
            'flagBitMask' => '192',
            'fullTextDataLength' => '0',
            'ignoreExtensions' => '',
            'indexExternalURLs' => '0',
            'maxExternalFiles' => '5',
            'minAge' => '24',
            'pdf_mode' => '20',
            'pdftools' => '/usr/bin/',
            'ppthtml' => '/usr/bin/',
            'unrtf' => '/usr/bin/',
            'unzip' => '/usr/bin/',
            'useMysqlFulltext' => '0',
            'xlhtml' => '/usr/bin/',
        ],
        'redirects' => [
            'showCheckIntegrityInfoInReports' => '1',
            'showCheckIntegrityInfoInReportsSeconds' => '86400',
        ],
        'scheduler' => [
            'maxLifetime' => '1440',
        ],
    ],
    'FE' => [
        'cacheHash' => [
            'enforceValidation' => true,
            'excludedParameters' => [
                'L',
                'mtm_campaign',
                'mtm_keyword',
                'mtm_kwd',
                'mtm_source',
                'mtm_medium',
                'mtm_content',
                'mtm_cid',
                'mtm_group',
                'mtm_placement',
                'pk_campaign',
                'pk_kwd',
                '_stg_debug',
                'utm_source',
                'utm_medium',
                'utm_campaign',
                'utm_term',
                'utm_content',
                'utm_id',
                'utm_source_platform',
                'utm_creative_format',
                'utm_marketing_tactic',
                'gtm_debug',
                '_ga',
                '_gl',
                'gad',
                'gad_source',
                'gbraid',
                'gclid',
                'dclid',
                'wbraid',
                'fbclid',
                'msclkid',
                'hsa_acc',
                'hsa_ad',
                'hsa_cam',
                'hsa_grp',
                'hsa_kw',
                'hsa_mt',
                'hsa_net',
                'hsa_src',
                'hsa_tgt',
                'hsa_ver',
                'hsa_ol',
                'hsa_la',
                '_hsenc',
                '_hsmi',
                '__hssc',
                '__hstc',
                '__hsfp',
                'hsCtaTracking',
                'submissionGuid',
            ],
        ],
        'compressionLevel' => 9,
        'debug' => true,
        'disableNoCacheParameter' => true,
        'hidePagesIfNotTranslatedByDefault' => false,
        'lifetime' => 604800,
        'pageNotFoundOnCHashError' => true,
        'passwordHashing' => [
            'className' => 'TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\Argon2iPasswordHash',
            'options' => [],
        ],
    ],
    'GFX' => [
        'processor' => 'GraphicsMagick',
        'processor_effects' => false,
        'processor_enabled' => true,
        'processor_path' => '/usr/local/bin/',
    ],
    'LOG' => [
        'TYPO3' => [
            'CMS' => [
                'deprecations' => [
                    'writerConfiguration' => [
                        'notice' => [
                            'TYPO3\CMS\Core\Log\Writer\FileWriter' => [
                                'disabled' => false,
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
    'MAIL' => [
        'defaultMailFromAddress' => 'noreply@typo3-13.wwagner.info',
        'defaultMailFromName' => 'Wolfgang Wagner',
        'transport' => 'sendmail',
        'transport_sendmail_command' => '/usr/sbin/sendmail -t',
        'transport_smtp_encrypt' => '',
        'transport_smtp_password' => '',
        'transport_smtp_server' => '',
        'transport_smtp_username' => '',
    ],
    'SYS' => [
        'UTF8filesystem' => true,
        'caching' => [
            'cacheConfigurations' => [
                'hash' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                ],
                'pages' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'options' => [
                        'compression' => true,
                    ],
                ],
                'rootline' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'options' => [
                        'compression' => true,
                    ],
                ],
            ],
        ],
        'ddmmyy' => 'd.m.Y',
        'devIPmask' => '*',
        'displayErrors' => 1,
        'encryptionKey' => '18d893f25a22164c1b3e3993bd57f911fbf94667514b42b99491c5aab0dbbb3d17c186c821707b35bdd1d071b39b1be0',
        'exceptionalErrors' => 12290,
        'features' => [
            'frontend.cache.autoTagging' => true,
            'security.frontend.enforceContentSecurityPolicy' => false,
            'security.frontend.reportContentSecurityPolicy' => false,
        ],
        'sitename' => 'My Project',
        'systemLocale' => 'en_GB',
        'systemMaintainers' => [
            1,
            8,
        ],
    ],
];
